#!/usr/bin/env python3
"""Generate the hardware localization companion without drifting from coroutine.lua."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SECTIONS = ['trivial errors', 'tests for multiple yield/resume arguments', 'yields in tail calls', 'recursive', 'sieve', 'bank-0 C stack (a full lua_resume + setjmp buffer + luaV_execute per', 'level), so the chain depth = number of primes found is hard-capped at', 'ldo.c) raises a clean C stack overflow instead of overrunning the', 'segment. gennum=8 yields 4 primes (2,3,5,7) with margin. The old', 'gennum=46 (14 primes) actually overran the segment and corrupted', 'memory; it only appeared to pass under GoldenGate.', 'yielding across C boundaries', 'unyieldable C call', 'errors in coroutines', 'co-routines x for loop', 'access to locals of collected corroutines', 'old bug: attempt to resume itself', 'other old bug when attempting to resume itself', 'bug in 5.4.1', "attempt to resume 'normal' coroutine", 'infinite recursion of coroutines', 'access to locals of erroneous coroutines', "overwrite previous position of local `a'", 'leaving a pending coroutine open', "repeat tests with larger constants (to use 'K' opcodes)", 'getuptable & setuptable', 'tests for coroutine API', 'testing coroutines with C bodies', 'testing chain of suspendable C calls', "three '34's (one from each pending C call)", 'testing yields with continuations', 'original arguments', 'arguments left from fist resume', 'arguments to last resume', 'error message and nothing more', 'check arguments to pcallk', 'bug in nCcalls']
PREFIX = """-- Generated by tools/generate-cobeacon.py; edit coroutine.lua instead.
-- B markers locate sections (some mark explanatory comments, not operations).
io.stdout:setvbuf("no")
print("B0 coroutine diagnostic entered")
local _bn = 0
local function _B(s) _bn = _bn + 1; io.write("B", _bn, " ", s, "\\n"); io.flush() end

"""


def generate(source):
    for section in SECTIONS:
        anchor = "-- " + section
        # Match a complete comment line to avoid partial/ambiguous matches.
        lines = source.splitlines(keepends=True)
        matches = [i for i, line in enumerate(lines) if line.rstrip().replace('"', '') == anchor]
        if len(matches) != 1:
            raise ValueError(f"Beacon anchor missing or ambiguous: {section}")
        lines.insert(matches[0], "_B(" + json.dumps(section) + ")\n")
        source = "".join(lines)
    source = source.replace('  print "OK"; return',
                            '  print "OK"; print "BEACON DONE (C API harness skipped)"; return')
    return PREFIX + source + '\nprint "BEACON DONE"\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate((ROOT / "tests/coroutine.lua").read_text())
    target = ROOT / "tests/cobeacon.lua"
    if args.check:
        if target.read_text() != result:
            raise SystemExit("cobeacon.lua is stale; run tools/generate-cobeacon.py")
    else:
        target.write_text(result)


if __name__ == "__main__":
    main()
