#!/usr/bin/bash
# iix provided by Golden Gate: https://juiced.gs/store/golden-gate/
COMP="iix-compile"
COMPFLAGS="-I -P"
OBJS="lapi lauxlib lbaselib lcode lcorolib lctype ldblib ldebug ldo ldump lfunc lgc linit liolib llex lmathlib lmem loadlib lobject lopcodes loslib lparser lstate lstring lstrlib ltable ltablib ltm lundump lutf8lib lzio lvm"

# clean house
if [ "$1" == "clean" ]; then
  rm -f -- *.sym *.a *.b *.d *.e *.root
  exit
fi

do_compile() {
      echo "$1"
      rm -f -- "${1}".root "${1}".a "${1}".sym
      "$COMP" "$COMPFLAGS" "${1}".c "$2"
      if [ $? -ne 0 ]; then
        rm -f "${1}".root "${1}".a
      fi
}

# compile OBJS
for file in $OBJS
do
    # check if there is an object file for the current file
    if [ -s "${file}".a ]; then
      # check and see if the object file is older than the source file
      if [ "${file}".a -ot "${file}".c ]; then
        DOIT=1
      else
        DOIT=0
      fi
    else
      DOIT=1
    fi
    if [ $DOIT -eq 1 ]; then
      do_compile "$file"
    fi
done

do_compile "lua"
do_compile "luac"

# create library
LINKFILES=""
for file in $OBJS
do
  LINKFILES="$LINKFILES +$file.a"
done
#echo $LINKFILES
#iix MakeLib lua.lib $LINKFILES
iix link +B lua $OBJS KEEP=lua
iix link +B luac $OBJS KEEP=luac
#iix link luac lparser lcode lapi lauxlib ldump lundump lobject lvm lopcodes lzio lctype ltable lfunc ldebug llex ldo ltm lgc lstring lmem lstate KEEP=luac
